---
title: "Jeopardy Daily Double Locations"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: sandstone
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Monthly deaths from bronchitis, emphysema and asthma in the
UK, 1974–1979 (Source: P. J. Diggle, 1990, Time Series: A
Biostatistical Introduction. Oxford, table A.3)

```{r, warning = FALSE, error = FALSE, message = FALSE}
library(readr)
library(plotly)
library(forcats)
library(lubridate)
library(tidyr)

dd <- read_csv("data/data_final.csv") 
dd <- dd %>% 
  rename("dd_weighting" = "weight") %>% 
  mutate(y_pos = factor(y_pos, levels = c(1, 2, 3, 4, 5)),
         y_pos = factor(y_pos, levels = rev(levels(y_pos))),

         x_pos = factor(x_pos, levels = c(1, 2, 3, 4, 5, 6)),
         x_pos = fct_recode(x_pos, 
                            "Category 1" = "1",
                            "Category 2" = "2",
                            "Category 3" = "3",
                            "Category 4" = "4",
                            "Category 5" = "5",
                            "Category 6" = "6")) 
```


Column 
-----------------------------------------------------------------------

### Daily Double Locations by Year

```{r}
daily_double_year <- dd %>% 
  mutate(year = year(air_date)) %>% 
  group_by(x_pos, y_pos, year) %>%
  summarise(number_of_doubles = sum(dd_weighting)) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  mutate(Percent = round(number_of_doubles/sum(number_of_doubles) * 100), 
         digits = 2) %>% 
  nest()

daily_double_year %>% 
  unnest() %>% 
  plot_ly(
    x = ~ x_pos,
    y = ~ y_pos,
    z = ~ Percent,
    frame = ~ year,
    hovertemplate = paste("Daily Double Percent: %{z:,}%<br>",
                          "<extra></extra>"),
    colors = "Blues",
    type = 'heatmap'
) %>% 
  layout(title = list(text = ""), 
         xaxis = list(title = "", 
                      side = 'top'),
          yaxis = list(title = ""))


```



Column {data-width=350}
-----------------------------------------------------------------------

### Daily Doubles Round 1

```{r}
# Create heat maps by round
# Round 1
dd_1 <- dd %>% 
  filter(round == "1") %>%
  mutate(y_pos = fct_recode(y_pos,
                            "200" = "1",
                            "400" = "2",
                            "600" = "3",
                            "800" = "4",
                            "1000" = "5")) %>% 
  group_by(x_pos, y_pos) %>% 
  summarise(number_of_doubles = sum(dd_weighting)) %>% 
  mutate(Percent = round(number_of_doubles/2476*100, digits = 2)) %>%
  plot_ly(
    x = ~ x_pos,
    y = ~ y_pos,
    z = ~ Percent,
    hovertemplate = paste("Daily Double Percent: %{z:,}%<br>",
                          "<extra></extra>"),
    colors = "Blues",
    type = 'heatmap'
    ) %>%
  layout(title = list(text = ""), 
         xaxis = list(title = "", 
                      side = 'top'),
         yaxis = list(title = ""))
dd_1


```

### Daily Doubles in Round 2

```{r}
#Round 2
dd_2 <- dd %>%
  filter(round == "2") %>%
  mutate(y_pos = fct_recode(y_pos,
                            "400" = "1",
                            "800" = "2",
                            "1200" = "3",
                            "1600" = "4",
                            "2000" = "5")) %>% 
  group_by(x_pos, y_pos) %>% 
  summarise(number_of_doubles = sum(dd_weighting)) %>% 
  mutate(Percent = round(number_of_doubles/4887*100, digits = 2)) %>%
  plot_ly(
    x = ~ x_pos,
    y = ~ y_pos,
    z = ~ Percent,
    hovertemplate = paste("Daily Double Percent: %{z:,}%<br>",
                          "<extra></extra>"),
    colors = "Blues",
    type = 'heatmap'
    ) %>%
  layout(title = list(text = ""), 
         xaxis = list(title = "", 
                      side = 'top'), 
         yaxis = list(title = ""))
dd_2
```

